name: CI wget kernels

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          VERSION.TXT
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2.3.5
    - name: Run a one-line script
      run: echo Hello, world!
    #- name: Run a multi-line script
      #run: |
        #echo Add other actions to build,
        #echo test, and deploy your project.
    - name: mkdir downloads
      run: mkdir downloads

    - name: wget Dependencies kernels
      uses: wei/wget@v1.1.1
      with:
        args: -O downloads/kernels.tar.gz https://cloud.3mdeb.com/index.php/s/UQQVYrNIhg7ddwj/download
    - run: gzip -k -v -d downloads/*.tar.gz
    - run: xz -v -e -9 --threads=0 downloads/*.tar
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          downloads/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

